### ISSUE TITLE
Cannot import Amply from pulp

### ISSUE THREAD

**Issue by H3yfinn** [OSeMOSYS/simplicity#9]
Putting this here because it only occured because i was trying to use simplicity. It doesnt happen in our standard use of Otoole/Osemosys.

It's something i noticed while trying to run: _otoole convert datapackage datafile simplicity/OSeMOSYS-simplicity-11a3a26/datapackage.json ./simplicity.txt_ 
**Error**: Cannot import Amply from pulp
>   env\Lib\site-packages\otoole\preprocess\datafile_to_datapackage.py 
**Fix**:
-installed amply using **pip install amply**
-changed datafile_to_datapackage.py so it does: import amply as Amply
-It works. 

Also just to note, simplicity doesnt work with Otoole v1 because it cannot do the datapackage conversion anymore.

**Comment by H3yfinn** [comment]
I see the recent update. Just another note, the DiscountRateStorage csv is not in the dataset that is downloaded via wget. I will close this comment tomorrow.
EDIT: i see the admin for this repo can hide this comment. I'll leave that to them then (:

**Comment by willu47** [comment]
Thanks for the report @H3yfinn. I've now created the new version of simplicity v1.0 and updated the readme. Let me know if you have any other problems.
